require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable

Layout/LineLength:
  Max: 140
  Exclude:
   - 'config/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Metrics/ClassLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

