# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/masters" do
  # This should return the minimal set of attributes required to create a valid
  # Master. As you add validations to Master, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Master.create! valid_attributes
      get masters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      master = Master.create! valid_attributes
      get master_url(master)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_master_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      master = Master.create! valid_attributes
      get edit_master_url(master)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Master" do
        expect do
          post masters_url, params: { master: valid_attributes }
        end.to change(Master, :count).by(1)
      end

      it "redirects to the created master" do
        post masters_url, params: { master: valid_attributes }
        expect(response).to redirect_to(master_url(Master.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Master" do
        expect do
          post masters_url, params: { master: invalid_attributes }
        end.not_to change(Master, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post masters_url, params: { master: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested master" do
        master = Master.create! valid_attributes
        patch master_url(master), params: { master: new_attributes }
        master.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the master" do
        master = Master.create! valid_attributes
        patch master_url(master), params: { master: new_attributes }
        master.reload
        expect(response).to redirect_to(master_url(master))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        master = Master.create! valid_attributes
        patch master_url(master), params: { master: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested master" do
      master = Master.create! valid_attributes
      expect do
        delete master_url(master)
      end.to change(Master, :count).by(-1)
    end

    it "redirects to the masters list" do
      master = Master.create! valid_attributes
      delete master_url(master)
      expect(response).to redirect_to(masters_url)
    end
  end
end
