name: CI checks
on:
  push:
  pull_request:
    branches: [ $protected-branches, $default-branch]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: CI
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
        env:
          RUBY_YJIT_ENABLE: 1  
          RAILS_ENV: test

      - name: Set up PostgreSQL database
        run: |
          bundle exec rails db:create db:migrate

      - name: Check code style
        run: |
          bundle exec rubocop
      
      - name: Run rspec
        run: |
          bundle exec rspec

      - name: Check bundle audit
        run: |
          bundle exec bundler-audit