name: Run RSpec tests
on: [push, pull_request]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Check code style
        run: |
          bundle exec rubocop
      
      - name: Run rspec
        run: |
          bundle exec rspec

      - name: Check bundle audit
        env:
          RAILS_ENV: test
        run: |
          bundle exec bundler-audit